(function(){function b(b,c,g,q){return isNaN(b)?c:b<g?g:b>q?q:b}function Ia(b,c){for(var g={},q=1;4>q;q++){var f=b["wave"+q];if(f)for(var r in f)!isNaN(f[r])&&r in Ja&&(g[Ja[r]+q]=f[r])}if(c)for(r in Ka)r in g||(g[r]=0);return g}function db(b,c,g,q,E){var r={},H=0,w;for(propName in c)w=pb[propName],"DOT_COLOR"!=propName&&w&&c[propName]!=b[w]&&(r[w]=c[propName],H++);H&&La.run(b,r,g,1E3*q,E);"DOT_COLOR"in c&&c.DOT_COLOR!=b.dotColor?qb.run(b,"dotColor",c.DOT_COLOR,f.lin(),1E3*q,E):H||rb.seconds(q)}function E(Y,
c){function g(a){a=p.width=Z.clientWidth;var c=p.height=Z.clientHeight;Ma&&(la=c/a>Ka?a/Na:c/Oa);N&&($=A+x*a,aa=y+z*c)}function q(a,c,b){b=ma/(na+b);return{x:b*a,y:b*c,alpha:1>b?b*b:1,scale:b}}function cb(){var a,c,b,d,f,k,h;oa=Math.sqrt(ba*ba+ca*ca);m=ba/oa||1E-4;n=-ca/oa||1E-4;B=Math.sin(ha+e.angle);t=Math.cos(ha+e.angle);d=[[m*m+n*n*t,m*n*(1-t),n*B],[m*n*(1-t),n*n+m*m*t,-m*B],[-n*B,m*B,(m*m+n*n)*t]];h=u;var l=[],g;for(g=0;3>g;g++)for(l[g]=[],b=0;3>b;b++)l[g][b]=d[g][0]*h[0][b]+d[g][1]*h[1][b]+
d[g][2]*h[2][b];u=l;p.width=p.width;O.fillStyle=pa;N?O.translate(p.width/2+$,p.height/2+aa):O.translate(p.width/2,p.height/2);Ma&&O.scale(la,la);for(l=da;l--;)for(d=4*l/da*P-Pa,g=h=Math.round(da*(2+qa*Math.cos(.5*d+.5*Math.PI))/ra);g--;)a=g/h*2*P-P,f=(sa+e.amp1*Math.sin(e.freq1*d+e.pha1))*(1-ia+ia*Math.sin(.5*d)),c=ta+e.amp2*Math.sin(e.freq2*a+e.pha2)+e.amp3*Math.sin(e.freq3*d+e.pha3),b=(f+c*Math.cos(a))*Math.cos(d),f=(f+c*Math.cos(a))*Math.sin(d),k=c*Math.sin(a)+ua*Math.sin(.5*d+Math.PI/2),a=u[0][0]*
b+u[0][1]*f+u[0][2]*k,c=u[1][0]*b+u[1][1]*f+u[1][2]*k,b=u[2][0]*b+u[2][1]*f+u[2][2]*k,b=q(a,c,b),f=va*b.scale,O.globalAlpha=b.alpha,0<f&&O.fillRect(b.x,b.y,f,f)}function r(a){var b=p.getBoundingClientRect();return{x:a.clientX-b.left-$,y:a.clientY-b.top-aa}}function H(a){wa=(new Date).getTime();wa-Qa>1E3/eb&&(s=r(a),Q=s.x-xa,R=s.y-ya,S=Math.sqrt(Q*Q+R*R),ja=Math.sqrt((s.x-p.width/2)*(s.x-p.width/2)+(s.y-p.height/2)*(s.y-p.height/2)),S&&ja<T&&(za=ja<F?1:(T-ja)/(T-F),Math.abs(Math.acos((Q*Ra+R*Sa)/(Ta*
S)))>Math.PI/2&&(I*=-1,ha=I*ea),Math.min(S,Ua)*J*za>Math.abs(e.angle)&&(Va.stop(),e.angle=I*Math.min(S,Ua)*J*za,ca=I*Q,ba=I*R,Va=La.run(e,{angle:0},f.powOut(3),Aa,C)),Ra=Q,Sa=R,Ta=S),xa=s.x,ya=s.y,Qa=wa)}function w(a){document.removeEventListener("mousemove",w);s=r(a);xa=s.x;ya=s.y;document.addEventListener("mousemove",H)}var Ba=document.getElementById(Y);if(Ba){E.instances[Y]&&E.instances[Y].destroy();E.instances[Y]=this;c||(c={});var d=Number.POSITIVE_INFINITY,h=Number.NEGATIVE_INFINITY,eb=30,Ua=
100,P=Math.PI,Pa=P/2,Ma=c.AUTO_SCALE,Na=b(c.VIEWPORT_WIDTH,800,100,d),Oa=b(c.VIEWPORT_HEIGHT,800,100,d),da=Math.round(b(c.DETALIZATION,180,1,d)),sa=b(c.TUBE_SIZE,220,1,d),fa=b(c.TUBE_DISTANCE,1E3,0,d),ea=b(c.ROTATION_SPEED,5,0,d)/1E3,Wa=P*b(c.INITIAL_ROTATION,0,0,d)/180,fb=b(c.INITIAL_ROTATION_DIRECTION,4.5,h,d),G=b(c.PERSPECTIVE_DISTORTION,1,.001,d),A=b(c.OFFSET_X,0,h,d),y=b(c.OFFSET_Y,0,h,d),x=b(c.PERCENTAGE_OFFSET_X,0,h,d)/100,z=b(c.PERCENTAGE_OFFSET_Y,0,h,d)/100,ta=b(c.TUBE_WIDTH,50,h,d),ra=b(c.MESH_RATIO,
14,.5,d),qa=b(c.MESH_DISTRIBUTION,0,-2,2),ia=b(c.TUBE_TORSION,.3,h,d),ua=b(c.TUBE_STRETCH,200,h,d),Xa=c.USE_MAIN_MORPHING,gb="MAIN_MORPHING_AUTOPLAY"in c?c.MAIN_MORPHING_AUTOPLAY:!0,Ya=b(c.MAIN_MORPHING_DURATION,2,0,d),hb=b(c.MAIN_MORPHING_DELAY,1,0,d),U=c.MAIN_MORPHING_TRANSITION_TYPE||"cubic",V=c.MAIN_MORPHING_STAGES||[],va=b(c.DOT_SIZE,2,0,d),pa=c.DOT_COLOR||"black",F=b(c.MOUSE_DISTANCE_MIN,20,0,d),T=b(c.MOUSE_DISTANCE_MAX,F+400,F+.001,d),J=b(c.MOUSE_SENSITIVITY,1,0,d)/1E3,Aa=1E3*b(c.INERTIAL_TIME,
2,0,d),ib=c.SURFACE_INITIAL_DISTORTION||{wave1:{amplitude:0,frequency:0,phase:0},wave2:{amplitude:0,frequency:0,phase:0},wave3:{amplitude:0,frequency:0,phase:0}},ka=c.USE_SURFACE_MORPHING,Ca=c.USE_SURFACE_MOTION,Za=c.USE_SURFACE_SWING,jb="SURFACE_MORPHING_AUTOPLAY"in c?c.SURFACE_MORPHING_AUTOPLAY:!0,$a=b(c.SURFACE_MORPHING_DURATION,2,0,d),kb=b(c.SURFACE_MORPHING_DELAY,1,0,d),W=c.SURFACE_MORPHING_TRANSITION_TYPE||"cubic",v=c.SURFACE_MORPHING_STAGES||[];if(Ca&&ka&&v.length)for(var D=1;4>D;D++)if(c["WAVE_"+
D+"_MOTION_SPEED"])for(var k=v.length;k--;){var ga=v[k]["wave"+D];ga&&"phase"in ga&&delete ga.phase}if(Za)for(D=1;4>D;D++){var X=c["WAVE_"+D+"_SWING_SETTINGS"];if(X){for(var K in X){var l=X[K];if(l){if(ka)for(k=v.length;k--;)(ga=v[k]["wave"+D])&&K in ga&&delete ga[K];"type"in l&&(l.wave=("function"===typeof l.type?l.type:sb[l.type])||Da.sin,delete l.type);"amplitude"in l&&isNaN(l.amplitude)&&delete l.amplitude;"frequency"in l&&isNaN(l.frequency)&&delete l.frequency;"phase"in l&&isNaN(l.phase)&&delete l.phase}}X.phase&&
Ca&&(c["WAVE_"+D+"_MOTION_SPEED"]=0)}}var Ea=c.WAVE_1_MOTION_SPEED,Fa=c.WAVE_2_MOTION_SPEED,Ga=c.WAVE_3_MOTION_SPEED,na=fa/G,ma=1E3/G,Z=function(){var a=document.createElement("div");lb.set(a,{position:"relative",width:"100%",height:"100%",top:0,left:0,margin:0,userSelect:"none",MozUserSelect:"none",WebkitUserSelect:"none",MsUserSelect:"none",KhtmlUserSelect:"none",userDrag:"none",WebkitUserDrag:"none",overflow:"hidden",cursor:"default"});a.setAttribute("unselectable","on");Ba.appendChild(a);return a}(),
p=function(){var a=document.createElement("canvas");lb.set(a,{position:"absolute",width:"100%",height:"100%",top:0,left:0,margin:0});Z.appendChild(a);return a}(),O=p.getContext("2d"),C=new tb,e=function(){var a={set:function(a){for(var b in a)this[b]=a[b]},angle:0},b=Ia(ib,!0),c;for(c in b)a[c]=b[c];return a}(),ab=P*fb/6-Pa,ca=Math.cos(ab),ba=Math.sin(ab),I=1,ha=ea,Va={stop:function(){}},B=Math.sin(Wa),t=Math.cos(Wa),oa,m=ba,n=-ca,u=[[m*m+n*n*t,m*n*(1-t),n*B],[m*n*(1-t),n*n+m*m*t,-m*B],[-n*B,m*B,
(m*m+n*n)*t]],ja,za,s,Ra=0,Sa=0,Ta=0,Q,R,S,xa,ya,wa,Qa=(new Date).getTime(),la,$=0,aa=0,N=A||y||x||z,Ka=Oa/Na;this.resize=function(){g()};this.destroy=function(){E.instances[Y]=null;C.removeAllListeners();L&&L.clear();M&&M.clear();window.removeEventListener("resize",g);document.removeEventListener("mousemove",w);document.removeEventListener("mousemove",H);Z.removeChild(p);Ba.removeChild(Z);Ba=Y=c=d=h=eb=Ua=P=Pa=da=sa=ea=G=Wa=fb=ta=ra=qa=ia=ua=Ma=Na=Oa=va=pa=F=T=J=Aa=ib=Xa=ka=Ca=Za=gb=Ya=hb=U=V=jb=
$a=kb=W=v=Ea=Fa=Ga=fa=na=ma=A=y=x=z=Z=p=O=C=e=ca=ba=I=ha=Va=B=t=oa=m=n=u=ja=za=s=Ra=Sa=Ta=Q=R=S=xa=ya=wa=Qa=L=M=la=g=q=cb=r=H=w=N=$=aa=ab=null;for(K in this)delete this[K];this.resize=this.destroy=this.mainMorphTo=this.surfaceMorphTo=function(){}};this.mainMorphTo=function(a){if(Xa&&V.length){var b;a&&"object"===typeof a?b=a:!isNaN(a)&&0<=a&&a<V.length&&!(a-Math.floor(a))&&(b=V[a]);b&&db(this,b,"function"===typeof U?U:Ha[U],Ya,C)}};this.surfaceMorphTo=function(a){if(ka&&v.length){var b;a&&"object"===
typeof a?b=a:!isNaN(a)&&0<=a&&a<v.length&&!(a-Math.floor(a))&&(b=v[a]);b&&La.run(e,Ia(b),"function"===typeof W?W:Ha[W],1E3*$a,C)}};Object.defineProperties(this,{detalization:{get:function(){return da},set:function(a){da=Math.round(b(a,60,1,d))},configurable:!0},tubeSize:{get:function(){return sa},set:function(a){sa=b(a,220,1,d)},configurable:!0},tubeDistance:{get:function(){return fa},set:function(a){fa=b(a,1E3,0,d);na=fa/G;ma=1E3/G},configurable:!0},rotationSpeed:{get:function(){return 1E3*ea},set:function(a){ea=
b(a,5,0,d)/1E3;ha=I*ea},configurable:!0},tubeWidth:{get:function(){return ta},set:function(a){ta=b(a,50,h,d)},configurable:!0},tubeTorsion:{get:function(){return ia},set:function(a){ia=b(a,.3,h,d)},configurable:!0},tubeStretch:{get:function(){return ua},set:function(a){ua=b(a,200,h,d)},configurable:!0},perspectiveDistortion:{get:function(){return G},set:function(a){G=b(a,1,.001,d);na=fa/G;ma=1E3/G},configurable:!0},offsetX:{get:function(){return A},set:function(a){N=(A=b(a,0,h,d))||y||x||z;$=A+x*
p.width},configurable:!0},offsetY:{get:function(){return y},set:function(a){y=b(a,0,h,d);N=A||y||x||z;aa=y+z*p.height},configurable:!0},percentageOffsetX:{get:function(){return 100*x},set:function(a){x=b(a,0,h,d)/100;N=A||y||x||z;$=A+x*p.width},configurable:!0},percentageOffsetY:{get:function(){return 100*z},set:function(a){z=b(a,0,h,d)/100;N=A||y||x||z;aa=y+z*p.height},configurable:!0},dotSize:{get:function(){return va},set:function(a){va=b(a,2,0,d)},configurable:!0},dotColor:{get:function(){return pa},
set:function(a){pa=a||"black"},configurable:!0},meshDistribution:{get:function(){return qa},set:function(a){qa=b(a,.3,-2,2)},configurable:!0},meshRatio:{get:function(){return ra},set:function(a){ra=b(a,4,.5,d)},configurable:!0},mouseDistanceMin:{get:function(){return F},set:function(a){F=b(a,20,0,T-1E-4)},configurable:!0},mouseDistanceMax:{get:function(){return T},set:function(a){T=b(a,F+400,F+.001,d)},configurable:!0},mouseSensitivity:{get:function(){return J},set:function(a){var c=J;(J=b(a,1,0,
d)/1E3)&&!c?document.addEventListener("mousemove",w):c&&!J&&(document.removeEventListener("mousemove",w),document.removeEventListener("mousemove",H))},configurable:!0},inertialTime:{get:function(){return Aa},set:function(a){Aa=1E3*b(a,2,0,d)},configurable:!0},wave1Amplitude:{get:function(){return e.amp1},set:function(a){e.amp1=a},configurable:!0},wave2Amplitude:{get:function(){return e.amp2},set:function(a){e.amp2=a},configurable:!0},wave3Amplitude:{get:function(){return e.amp3},set:function(a){e.amp3=
a},configurable:!0},wave1Frequency:{get:function(){return e.freq1},set:function(a){e.freq1=a},configurable:!0},wave2Frequency:{get:function(){return e.freq2},set:function(a){e.freq2=a},configurable:!0},wave3Frequency:{get:function(){return e.freq3},set:function(a){e.freq3=a},configurable:!0},wave1Phase:{get:function(){return e.pha1},set:function(a){e.pha1=a},configurable:!0},wave2Phase:{get:function(){return e.pha2},set:function(a){e.pha2=a},configurable:!0},wave3Phase:{get:function(){return e.pha3},
set:function(a){e.pha3=a},configurable:!0}});window.addEventListener("resize",g);g();if(Xa&&gb&&V.length){var M=new mb;M.delay=hb;for(var k=0,bb=V.length;k<bb;k++)M.addTask(db,this,V[k],"function"===typeof U?U:Ha[U],Ya,C);M.addQueue(M);M.run()}if(ka&&jb&&v.length){var L=new mb;L.delay=kb;k=0;for(bb=v.length;k<bb;k++)L.addTween(e,Ia(v[k]),"function"===typeof W?W:Ha[W],$a,C);L.addQueue(L);L.run()}if(Ca){var nb=function(){var a={},b=0;Ea&&!isNaN(Ea)&&(a.pha1=Ea,b++);Fa&&!isNaN(Fa)&&(a.pha2=Fa,b++);Ga&&
!isNaN(Ga)&&(a.pha3=Ga,b++);return b?new ub(e,a,C):0}();nb&&nb.play()}if(Za)for(k=1;4>k;k++)if(X=c["WAVE_"+k+"_SWING_SETTINGS"])for(K in X){var ob=Ja[K];ob&&(new vb(e,ob+k,X[K],C)).play()}C.addListener(cb);J&&document.addEventListener("mousemove",w)}else alert("TubeAnimation ERROR: There is no element with the specified id")}var tb=jsband.Metronome,f=jsband.Ease,La=jsband.Tween,rb=jsband.Pause,qb=jsband.ColorTween,lb=jsband.CssProp,mb=jsband.Queue,vb=jsband.Swing,Da=jsband.Wave,ub=jsband.Motion,Ha=
{linear:f.lin(),quad:f.pow(2),cubic:f.pow(3),quart:f.pow(4),quint:f.pow(5),circ:f.circ(),sine:f.sin(),expo:f.exp(),elastic:f.osc2Out(),bounce:f.bncOut(),back:f.backOut()},sb={sine:Da.sin,linear:Da.triangle,pulse:Da.pulse},Ka={amp1:1,freq1:1,pha1:1,amp2:1,freq2:1,pha2:1,amp3:1,freq3:1,pha3:1},Ja={amplitude:"amp",frequency:"freq",phase:"pha"},pb={TUBE_SIZE:"tubeSize",TUBE_DISTANCE:"tubeDistance",DETALIZATION:"detalization",PERSPECTIVE_DISTORTION:"perspectiveDistortion",TUBE_WIDTH:"tubeWidth",TUBE_TORSION:"tubeTorsion",
TUBE_STRETCH:"tubeStretch",ROTATION_SPEED:"rotationSpeed",DOT_SIZE:"dotSize",DOT_COLOR:"dotColor",MESH_DISTRIBUTION:"meshDistribution",MESH_RATIO:"meshRatio"};E.instances={};window.TubeAnimation=E})();
